apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
resolvConf: /etc/resolv.conf.kubelet
enforceNodeAllocatable:
  - "system-reserved"
  - "pods"
# https://github.com/kubernetes/design-proposals-archive/blob/main/node/node-allocatable.md
systemReservedCgroup: "/system.slice"
systemReserved:
  memory: "${SYSTEM_RESERVED_MEMORY}Gi"
